In [1]:
import pandas as pd
import random

In [2]:
df = pd.read_csv("Final dataset.csv")
df.head()

,Student_Name,Degree,Major,CGPA,Skills,Interest_Area,Communication Skill Rating (1-5),Coding_Level,Recommended_Course,Why_Should_Prefer,Career_Roles_After_Course
0,Divya Singh,B.Sc,Statistics,8.37,"HTML, CSS",Web Development,2.0,Intermediate,Full Stack,Interest in Web Development with relevant back...,"Full Stack Developer, Web Developer"
1,Priya N,B.Tech,Electronics,6.77,Excel,Business Data,4.0,Advanced,Data Analysis (Power BI),Interest in Business Data with relevant backgr...,"Data Analyst, BI Analyst"
2,Pooja Singh,BBA,Business Administration,8.62,Python Basics,Data,5.0,Intermediate,Data Science,Interest in Data with relevant background and ...,"Data Scientist, Data Analyst"
3,Rohit Verma,Diploma,Computer Engineering,7.66,"HTML, CSS",Web Development,4.0,Beginner,Full Stack,Interest in Web Development with relevant back...,"Full Stack Developer, Web Developer"
4,Varun Yadav,BCA,Computer Applications,6.64,Excel,Business Data,2.0,Intermediate,Data Analysis (Power BI),Interest in Business Data with relevant backgr...,"Data Analyst, BI Analyst"

In [3]:
df["Recommended_Course"].unique()

array(['Full Stack', 'Data Analysis (Power BI)', 'Data Science',
       'Spring Boot', 'Deep Learning', 'Django', 'Machine Learning',
       'Cyber Security', 'Cloud Computing', 'MySQL'], dtype=object)

In [3]:
df["Degree"].unique()

array(['B.Sc', 'B.Tech', 'BBA', 'Diploma', 'BCA', 'B.Com'], dtype=object)

In [4]:
df["Major"].unique()

array(['Statistics', 'Electronics', 'Business Administration',
       'Computer Engineering', 'Computer Applications', 'IT', 'Marketing',
       'Commerce', 'Computer Science', 'Mathematics'], dtype=object)

In [71]:
df=df.drop(columns="Student_Name")

In [72]:
df.head()

,Degree,Major,CGPA,Skills,Interest_Area,Communication Skill Rating (1-5),Coding_Level,Recommended_Course,Why_Should_Prefer,Career_Roles_After_Course
0,B.Sc,Statistics,8.37,"HTML, CSS",Web Development,2.0,Intermediate,Full Stack,Interest in Web Development with relevant back...,"Full Stack Developer, Web Developer"
1,B.Tech,Electronics,6.77,Excel,Business Data,4.0,Advanced,Data Analysis (Power BI),Interest in Business Data with relevant backgr...,"Data Analyst, BI Analyst"
2,BBA,Business Administration,8.62,Python Basics,Data,5.0,Intermediate,Data Science,Interest in Data with relevant background and ...,"Data Scientist, Data Analyst"
3,Diploma,Computer Engineering,7.66,"HTML, CSS",Web Development,4.0,Beginner,Full Stack,Interest in Web Development with relevant back...,"Full Stack Developer, Web Developer"
4,BCA,Computer Applications,6.64,Excel,Business Data,2.0,Intermediate,Data Analysis (Power BI),Interest in Business Data with relevant backgr...,"Data Analyst, BI Analyst"

In [73]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [74]:
df.columns

Index(['degree', 'major', 'cgpa', 'skills', 'interest_area',
       'communication_skill_rating_(1-5)', 'coding_level',
       'recommended_course', 'why_should_prefer', 'career_roles_after_course'],
      dtype='object')

In [75]:
coding_level_map = {
    "beginner": "no_coding",
    "intermediate": "low_coding",
    "advanced": "high_coding"
}

df["coding_level"] = df["coding_level"].str.lower().map(coding_level_map)

In [76]:
from sklearn.preprocessing import MultiLabelBinarizer

df["skills"] = df["skills"].fillna("").apply(lambda x: x.lower().split(","))

mlb = MultiLabelBinarizer()
skills_encoded = pd.DataFrame(
    mlb.fit_transform(df["skills"]),
    columns=mlb.classes_
)

df = pd.concat([df, skills_encoded], axis=1)
df.drop(columns=["skills"], inplace=True)

In [77]:
df.head()

,degree,major,cgpa,interest_area,communication_skill_rating_(1-5),coding_level,recommended_course,why_should_prefer,career_roles_after_course,css,math,sql,communication,excel,html,java basics,networking basics,python,python basics,sql
0,B.Sc,Statistics,8.37,Web Development,2.0,low_coding,Full Stack,Interest in Web Development with relevant back...,"Full Stack Developer, Web Developer",1,0,0,0,0,1,0,0,0,0,0
1,B.Tech,Electronics,6.77,Business Data,4.0,high_coding,Data Analysis (Power BI),Interest in Business Data with relevant backgr...,"Data Analyst, BI Analyst",0,0,0,0,1,0,0,0,0,0,0
2,BBA,Business Administration,8.62,Data,5.0,low_coding,Data Science,Interest in Data with relevant background and ...,"Data Scientist, Data Analyst",0,0,0,0,0,0,0,0,0,1,0
3,Diploma,Computer Engineering,7.66,Web Development,4.0,no_coding,Full Stack,Interest in Web Development with relevant back...,"Full Stack Developer, Web Developer",1,0,0,0,0,1,0,0,0,0,0
4,BCA,Computer Applications,6.64,Business Data,2.0,low_coding,Data Analysis (Power BI),Interest in Business Data with relevant backgr...,"Data Analyst, BI Analyst",0,0,0,0,1,0,0,0,0,0,0

In [78]:
from sklearn.preprocessing import LabelEncoder

cat_cols = ["degree", "major", "interest_area", "coding_level"]

encoders = {}
for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

In [79]:
df.head()

,degree,major,cgpa,interest_area,communication_skill_rating_(1-5),coding_level,recommended_course,why_should_prefer,career_roles_after_course,css,math,sql,communication,excel,html,java basics,networking basics,python,python basics,sql
0,1,9,8.37,9,2.0,1,Full Stack,Interest in Web Development with relevant back...,"Full Stack Developer, Web Developer",1,0,0,0,0,1,0,0,0,0,0
1,2,5,6.77,2,4.0,0,Data Analysis (Power BI),Interest in Business Data with relevant backgr...,"Data Analyst, BI Analyst",0,0,0,0,1,0,0,0,0,0,0
2,3,0,8.62,3,5.0,1,Data Science,Interest in Data with relevant background and ...,"Data Scientist, Data Analyst",0,0,0,0,0,0,0,0,0,1,0
3,5,3,7.66,9,4.0,2,Full Stack,Interest in Web Development with relevant back...,"Full Stack Developer, Web Developer",1,0,0,0,0,1,0,0,0,0,0
4,4,2,6.64,2,2.0,1,Data Analysis (Power BI),Interest in Business Data with relevant backgr...,"Data Analyst, BI Analyst",0,0,0,0,1,0,0,0,0,0,0

In [80]:
target_col = "recommended_course"

# Keep ONLY numeric columns
X = df.drop(columns=[target_col]).select_dtypes(include=["int64", "float64"])
y = df[target_col]

In [81]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [82]:
def predict_top_courses(user_input):
    probs = model.predict_proba(user_input)[0]
    top_idx = probs.argsort()[-3:][::-1]
    return model.classes_[top_idx]

In [83]:
def prepare_user_input(user):
    row = {}

    for col in cat_cols:
        row[col] = encoders[col].transform([user[col]])[0]

    for skill in mlb.classes_:
        row[skill] = 1 if skill in user["skills"] else 0

    return pd.DataFrame([row])

In [84]:
def get_course_details(course):
    row = df[df["recommended_course"] == course].iloc[0]
    return row["why_should_prefer"], row["career_roles_after_course"]